version: '3'
services:
  remotediag:
    build: .
    container_name: remotediag
    restart: always
    ports:
      - "3004:3004"
    volumes:
      - ./uploads:/app/uploads
      - ./users.json:/app/users.json
      - ./tokens.json:/app/tokens.json
      - ./dist:/app/dist
      - ./dist_go:/app/dist_go
      - ./rc_tokens.json:/app/rc_tokens.json
      - ./static:/app/static
      - ./diag_profiles:/app/diag_profiles
      - ./remote_control.py:/app/remote_control.py
      - ./manage_users.py:/app/manage_users.py
      - ./manage_rc_tokens.py:/app/manage_rc_tokens.py
    env_file:
      - .env
